### ISSUE TITLE
Document software in dev.est

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/ESTools#10]
estools wiki
- [x] Supervisor
- [x] Wordpress
- [x] DHIS2 instances

**Comment by tokland** [comment]
That should cover all changes in dev.est, anything missing?

https://github.com/EyeSeeTea/ESTools/wiki

**Comment by adrianq** [comment]
Yes, I have also added the permalink settings doc to the wordpress section. We can keep updating the documentation if we forget about anything anyway. Thanks @tokland !
