### ISSUE TITLE
Create dhis installation script

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/ESTools#3]
- General idea:
   - Soft update -> Drop db and install a fresh new db
   - Hard update -> Download latest dhis build, git pull db or download, Drop db and install a fresh new db

- Script Requirements:
`
   dhis_installer [[--softupdate | -s]|[--hardupdate|-h]] <DBURI> [[--db] <SHORTCUT>  [-u <USER>] -p <PASSWD> -n <DBNAME>] [--war|-w <WARFILEURI> [--destDir <DESTDIR>|<SHORTCUT>]] [--activate-cron|-C] [--hours|-h <HOURS> --minutes|-m <MINUTES>] <SHORTCUT> [--deactivate-cron|-c] [--hours|-h <HOURS> --minutes|-m <MINUTES>] <SHORTCUT>`
```

<DBURI> → URI para descargarse la DB (fichero|repo git|url)
<SHORTCUT> → Atajo a las configuraciones listadas en el fichero /etc/dhis_installer/properties, que por defecto serán:
android-previous1 | android-previous2 | android-dev | android-current
o bien rellenar los parámetros -u -p y -n para conectarse
<USER> → Usuario de la DB postgres
<PASSWD> → Password de la DB postgres
<DBNAME> → Nombre de la DB postgres
<WARFILEURI> → URI para descargarse la DB
<HOURS> → La hora a configurar en cron
<MINUTES> → Los minutos a configurar en cron
```

- Use case
   - DB (https://github.com/dhis2/dhis2-demo-db)
   - WAR/GIT
       wget https://www.dhis2.org/downloads o de https://ci.dhis2.org
       wget https://ci.dhis2.org/job/dhis2-trunk/lastSuccessfulBuild/deployedArtifacts/download/artifact.1/

   - Needs to be executed nightly although it can be stopped on demand. A single entry in the crontab per dhis version

**Comment by tokland** [comment]
PR ready for review. 

Installed in android.dhis2.org. Current crontab:

```
00 03  * * * /usr/local/bin/dhis2-installer update dev
30 03  * * * /usr/local/bin/dhis2-installer update current
00 04  * * * /usr/local/bin/dhis2-installer update previous1
30 04  * * * /usr/local/bin/dhis2-installer update previous2
```

For more info see README:

https://github.com/EyeSeeTea/ESTools/tree/feature/dhis2-installer/DHIS2/installer

**Comment by adrianq** [comment]
@tokland I saw a couple of commits after you said PR was ready to be reviewed, is it actually ready?

**Comment by tokland** [comment]
Yes, they were minor cosmetic commits.
