### ISSUE TITLE
Notify on last day of month

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/ESTools#30]
ON last day of month -> email monthly summary (similar to what we have)
        [new] period summary
        (with %, since we have also a yearly total hours: 340h, 1 Mayo 2018 hasta el 31 Dec 2019)
    (deploy with WHO + tag HWF)

- [x] Use Gmail as SMTP to avoid messages going to spam
- [x] Move args to JSON file (as array)
- [x] Add new entry type 'end of month' notification with required params

**Comment by ifoche** [comment]
Verified, it has worked for the last day of month
