### ISSUE TITLE
Create Post-install script

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/ESTools#5]
- Add post-install script: It should run a set of dhis api calls after resetting the db
- Analyse if [this tool](https://github.com/baosystems/dish2) can be interested for our purposes
- Add a call for creating ‘ALL’ authority user.  The ‘superuser’ role in play.dhis2.org/demo doesn’t actually have true superuser privileges, as it’s missing the ‘ALL’ authority. So this means the ‘Admin’ user also doesn’t have that all-important ‘ALL’ authority.  All we really need is a ‘true superuser’ role with that single authority, and a ‘superuser’ user with this role.

**Comment by tokland** [comment]
I've updated the PR, I noticed something was wrong with the user <superuser>, even though there is no user with that username, it cannot be created. Switched to superadmin/Super123.
